name: uni_app_dm
description: 动漫主应用
homepage: http://git.91momo50.vip/flutter/uni-common.git
repository: http://git.91momo50.vip/flutter/uni-common.git

publish_to: 'https://pub.91momo50.vip'
version: 1.3.3

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  # 基类
  uni_base:
    version: ^1.3.2
    hosted:
      name: uni_base
      url: https://pub.91momo50.vip
  # 组件
  uni_widget:
    version: ^1.1.6
    hosted:
      name: uni_widget
      url: https://pub.91momo50.vip
  # 网络
  uni_http:
    version: ^1.2.6
    hosted:
      name: uni_http
      url: https://pub.91momo50.vip
  # 图片
  uni_image:
    version: ^1.0.6
    hosted:
      name: uni_image
      url: https://pub.91momo50.vip
  # 下拉刷新
  uni_refresh:
    version: ^1.0.1
    hosted:
      name: uni_refresh
      url: https://pub.91momo50.vip
  # 通用
  uni_app_base:
    version: ^1.0.8
    hosted:
      name: uni_app_base
      url: https://pub.91momo50.vip
  # 钱包
  uni_app_wallet:
    version: ^1.0.6
    hosted:
      name: uni_app_wallet
      url: https://pub.91momo50.vip
  # 游戏
  uni_app_game:
    version: ^1.0.4
    hosted:
      name: uni_app_game
      url: https://pub.91momo50.vip
  # 视频
  uni_app_video:
    version: ^1.0.0-bate.4
    hosted:
      name: uni_app_video
      url: https://pub.91momo50.vip
  # 社区
  uni_app_community:
    version: ^1.0.2
    hosted:
      name: uni_app_community
      url: https://pub.91momo50.vip
  # 创作中心
  uni_app_creator:
    version: ^1.0.4
    hosted:
      name: uni_app_creator
      url: https://pub.91momo50.vip
  # 我的
  uni_app_mine_cfox:
    version: ^1.0.0-bate.6
    hosted:
      name: uni_app_mine_cfox
      url: https://pub.91momo50.vip
# 覆盖依赖，本地调试
dependency_overrides:
  uni_app_base:
    path: ../../uni_sub_app/uni_app_base
  uni_app_wallet:
    path: ../../uni_sub_app/uni_app_wallet
  uni_app_community:
    path: ../../uni_sub_app/uni_app_community
  uni_app_creator:
    path: ../../uni_sub_app/uni_app_creator
  uni_app_video:
    path: ../../uni_sub_app/uni_app_video
  uni_app_mine:
    path: ../../uni_sub_app/uni_app_mine
  uni_app_game:
    path: ../../uni_sub_app/uni_app_game

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/dm/
    - assets/base/
    - assets/base_dm/
    - assets/game/
    - assets/game_dm/
    - assets/wallet/
    - assets/wallet_dm/
    - assets/widget/
    - assets/widget_dm/
    - assets/community/
    - assets/community_dm/
    - assets/mine/
    - assets/mine_dm/
    - assets/video/
    - assets/video_dm/
    - assets/creator/
    - assets/creator_dm/