name: uni_app_cfox
description: 彩狐视频主应用
homepage: http://git.91momo50.vip/flutter/uni-common.git
repository: http://git.91momo50.vip/flutter/uni-common.git

publish_to: 'https://pub.91momo50.vip'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  # 基类
  uni_base:
    version: ^1.2.0
    hosted:
      name: uni_base
      url: https://pub.91momo50.vip
  # 组件
  uni_widget:
    version: ^1.0.7
    hosted:
      name: uni_widget
      url: https://pub.91momo50.vip
  # 网络
  uni_http:
    version: ^1.1.7
    hosted:
      name: uni_http
      url: https://pub.91momo50.vip
  # 图片
  uni_image:
    version: ^1.0.4
    hosted:
      name: uni_image
      url: https://pub.91momo50.vip
  uni_app_base:
    path: ../../uni_sub_app/uni_app_base
  uni_app_creator:
    path: ../../uni_sub_app/uni_app_creator
  uni_app_game:
    path: ../../uni_sub_app/uni_app_game
  uni_app_wallet:
    path: ../../uni_sub_app/uni_app_wallet
  uni_app_community:
    path: ../../uni_sub_app/uni_app_community
  uni_app_video:
    path: ../../uni_sub_app/uni_app_video
  uni_app_up:
    path: ../../uni_sub_app/uni_app_up
  uni_app_mine_cfox:
    path: ../../uni_sub_app/uni_app_mine_cfox
  uni_app_douyin:
    path: ../../uni_sub_app/uni_app_douyin
# 覆盖依赖
dependency_overrides:
  uni_app_base:
    path: ../../uni_sub_app/uni_app_base
  uni_app_creator:
    path: ../../uni_sub_app/uni_app_creator
  uni_app_game:
    path: ../../uni_sub_app/uni_app_game
  uni_app_wallet:
    path: ../../uni_sub_app/uni_app_wallet
  uni_app_community:
    path: ../../uni_sub_app/uni_app_community
  uni_app_video:
    path: ../../uni_sub_app/uni_app_video
  uni_app_up:
    path: ../../uni_sub_app/uni_app_up
  uni_app_mine_cfox:
    path: ../../uni_sub_app/uni_app_mine_cfox
  uni_app_douyin:
    path: ../../uni_sub_app/uni_app_douyin
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/cfox/
    - assets/base/
    - assets/game/
    - assets/wallet/
    - assets/widget/
    - assets/video/
    - assets/community/
    - assets/mine/
    - assets/douyin/
    - assets/creator/