name: uni_app_cfox
description: 彩狐视频主应用
homepage:  http://gitlab.apollo.5achang.com/flutter/uni_app.git
repository:  http://gitlab.apollo.5achang.com/flutter/uni_app.git

publish_to: 'http://16.163.159.207:4000'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  # 基类
  uni_base:
    version: ^1.0.0-bate.2
    hosted:
      name: uni_base
      url: http://16.163.159.207:4000
  # 组件
  uni_widget:
    version: ^1.0.0-bate
    hosted:
      name: uni_widget
      url: http://16.163.159.207:4000
  # 网络
  uni_http:
    version: ^1.0.0-bate
    hosted:
      name: uni_http
      url: http://16.163.159.207:4000
  # 通用
  uni_app_base:
    version: ^1.0.0
    hosted:
      name: uni_app_base
      url: http://16.163.159.207:4000
  # 钱包
  uni_app_wallet:
    version: ^1.0.0
    hosted:
      name: uni_app_wallet
      url: http://16.163.159.207:4000
  # 游戏
  uni_app_game:
    version: ^1.0.0
    hosted:
      name: uni_app_game
      url: http://16.163.159.207:4000
  # 视频
  uni_app_video:
    version: ^1.0.0
    hosted:
      name: uni_app_video
      url: http://16.163.159.207:4000
  # 抖音
  uni_app_douyin:
    version: ^1.0.0
    hosted:
      name: uni_app_douyin
      url: http://16.163.159.207:4000
  # 社区
  uni_app_community:
    version: ^1.0.0
    hosted:
      name: uni_app_community
      url: http://16.163.159.207:4000
  # 创作中心
  uni_app_creator:
    version: ^1.0.0
    hosted:
      name: uni_app_creator
      url: http://16.163.159.207:4000
  # 我的
  uni_app_mine:
    version: ^1.0.0
    hosted:
      name: uni_app_mine
      url: http://16.163.159.207:4000

# 覆盖依赖，本地调试
dependency_overrides:
  uni_app_base:
    path: ../../uni_sub_app/uni_app_base
  uni_app_wallet:
    path: ../../uni_sub_app/uni_app_wallet
  uni_app_creator:
    path: ../../uni_sub_app/uni_app_creator
  uni_app_game:
    path: ../../uni_sub_app/uni_app_game
  uni_app_video:
    path: ../../uni_sub_app/uni_app_video
  uni_app_douyin:
    path: ../../uni_sub_app/uni_app_douyin
  uni_app_community:
    path: ../../uni_sub_app/uni_app_community
  uni_app_mine:
    path: ../../uni_sub_app/uni_app_mine
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/cfox/
    - assets/base/
    - assets/game/
    - assets/wallet/
    - assets/widget/
    - assets/video/
    - assets/community/
    - assets/mine/
    - assets/douyin/
    - assets/creator/
    - assets/up/